language: python

python:
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

install:
    - pip install .
    - pip install pycodestyle
    - pip install pytest
    - pip install coverage

script:
    - pycodestyle pandasvalidation.py test_pandasvalidation.py setup.py
    - coverage run -m pytest test_pandasvalidation
    - c- coverage report -m pandasvalidation.py

after_success:
    - codecov
