language: python

python:
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

before_install:
    - pip install coverage
    - pip install pytest
    - pip install pytest-pep8

script:
    - py.test pandasvalidation.py --pep8
    - coverage run -m py.test
    - coverage report --include pandasvalidation.py -m

after_success:
    - codecov
