language: python

python:
    - '3.5'
    - '3.6'

# whitelist
branches:
    only:
        - master

install:
    - pip install .
    - pip install pylint
    - pip install pytest
    - pip install coverage
    - pip install codecov

script:
    - pylint ./pdvalidation/validation.py ./tests/test_validation.py setup.py
    - coverage run -m pytest ./tests/test_validation.py
    - coverage report -m ./pdvalidate/validation.py

after_success:
    - codecov
