language: python

python:
    - '2.7'
    - '3.3'
    - '3.4'
    - '3.5'

# whitelist
branches:
    only:
        - master

before_install:
    - pip install pytest pytest-cov

script:
    - py.test
    - sphinx-build -nW -b html ./docs/source ./docs/build-html
