language: python

python:
    - '3.4'
    - '3.5'

# whitelist
branches:
    only:
        - master

before_install:
    - pip install pytest pytest-cov
    - pip install codecov

script:
    - py.test

after_success:
  - codecov
