language: python

python:
    - '3.4'
    - '3.5'

# whitelist
branches:
    only:
        - master

before_install:
    - pip install codecov
    - pip install pytest pytest-cov

script:
    py.test --cov=pandasvalidation.py

after_success:
  - codecov